// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3unu7Ga9VoC4K7UxDprt9q
// Component: 6KGq7ysfCBAp

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import NavBar from "../../NavBar"; // plasmic-import: RWvIvrMYqfam/component
import Button from "../../Button"; // plasmic-import: C340TtQ1qMJ_/component
import ProductCard from "../../ProductCard"; // plasmic-import: 4Y9rk9do20W5/component
import Rating from "../../Rating"; // plasmic-import: wsRSyq_ruxlY/component
import EmojiValueProps from "../../EmojiValueProps"; // plasmic-import: l8qF1Ymn2krC/component
import Value from "../../Value"; // plasmic-import: 7dtSRzTgoyFA/component
import Footer from "../../Footer"; // plasmic-import: SNxDYAIWsvky/component

import { useScreenVariants as useScreenVariantskawom9Dsb4U2 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: Kawom9dsb4u2/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 3unu7Ga9VoC4K7UxDprt9q/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: 6KGq7ysfCBAp/css

import MenuIcon from "./icons/PlasmicIcon__Menu"; // plasmic-import: gtiXXUGcCZ-V/icon
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: EZI3azBNTV_Y/icon
import PlaneIcon from "./icons/PlasmicIcon__Plane"; // plasmic-import: XxPNNHEnmEve/icon
import DocumentIcon from "./icons/PlasmicIcon__Document"; // plasmic-import: -P99mQT_CbUV/icon
import LockIcon from "./icons/PlasmicIcon__Lock"; // plasmic-import: NCa3W2kHqQxI/icon
import SpeakerphoneIcon from "./icons/PlasmicIcon__Speakerphone"; // plasmic-import: scXQhpKWuZgC/icon
import MedalIcon from "./icons/PlasmicIcon__Medal"; // plasmic-import: tpxER-BVIeaz/icon
import LeafIcon from "./icons/PlasmicIcon__Leaf"; // plasmic-import: 3wr_qxFAuywn/icon
import ShoeIcon from "./icons/PlasmicIcon__Shoe"; // plasmic-import: iIrnPESRX7_V/icon
import PeaceIcon from "./icons/PlasmicIcon__Peace"; // plasmic-import: uS7rOhunbD6K/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {
  container42?: React.ReactNode;
};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>("container42");

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  navBar?: Flex__<typeof NavBar>;
  container3?: Flex__<"div">;
  h1?: Flex__<"h1">;
  container4?: Flex__<"div">;
  container?: Flex__<"div">;
  emojiValueProps?: Flex__<typeof EmojiValueProps>;
  columns?: Flex__<"div">;
  container42?: Flex__<"div">;
  container5?: Flex__<"div">;
  container6?: Flex__<"div">;
  container434?: Flex__<"div">;
  container433?: Flex__<"div">;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantskawom9Dsb4U2()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicHomepage.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicHomepage.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicHomepage.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicHomepage.pageMetadata.description}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
          />

          <section className={classNames(projectcss.all, sty.section__vu9Dp)}>
            <Stack__
              as={"div"}
              data-plasmic-name={"container3"}
              data-plasmic-override={overrides.container3}
              hasGap={true}
              className={classNames(projectcss.all, sty.container3)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___0HqSs)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__qXwoE)}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"New collection!"}
                  </h1>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nwb7L
                    )}
                  >
                    {
                      "A nam quisque orci ut vestibulum eget sem aliquet a dictumst condimentum ad quam porta a inceptos consectetur sagittis a a commodo ridiculus tempor egestas."
                    }
                  </div>
                </Stack__>
                <Button
                  className={classNames("__wab_instance", sty.button__pPjVz)}
                  colors={"black"}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(projectcss.all, sty.svg___6J3Uo)}
                      role={"img"}
                    />
                  }
                  rounded={true}
                  showEndIcon={true}
                  size={"large"}
                  submitsForm={true}
                >
                  {"Shop"}
                </Button>
              </Stack__>
            </Stack__>
          </section>
          <section className={classNames(projectcss.all, sty.section__zJlnO)}>
            <div
              data-plasmic-name={"container4"}
              data-plasmic-override={overrides.container4}
              className={classNames(projectcss.all, sty.container4)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__epq5A)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xbthF
                  )}
                >
                  {"Featured"}
                </div>
                <Button
                  className={classNames("__wab_instance", sty.button__y2E)}
                  colors={"link"}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(projectcss.all, sty.svg__wmTTm)}
                      role={"img"}
                    />
                  }
                  showEndIcon={true}
                  submitsForm={true}
                >
                  {"See more"}
                </Button>
              </div>
            </div>
            <Stack__
              as={"div"}
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              hasGap={true}
              className={classNames(projectcss.all, sty.container)}
            >
              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___5Kdle
                )}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe14.png",
                  fullWidth: 840,
                  fullHeight: 840,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__dUt3B)}
                    rating={"four"}
                  />
                }
                tags={
                  <Button
                    colors={"lightGray"}
                    size={"small"}
                    submitsForm={true}
                  >
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__j6JO0
                  )}
                >
                  {"ADIDAS ULTRABOOST DNA X LEGO\u00ae PLATES SHOES"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bEGmK
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>
              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___5ZUwp
                )}
                dollars={"79"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe15.png",
                  fullWidth: 864,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__wedr)}
                    rating={"threeHalf"}
                  />
                }
                tags={
                  <Button
                    colors={"lightGray"}
                    size={"small"}
                    submitsForm={true}
                  >
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uq1Mo
                  )}
                >
                  {"Nike Air Zoom Pegasus 38"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___6Iv0F
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__z7TaK)}
                dollars={"64"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe16.png",
                  fullWidth: 840,
                  fullHeight: 840,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__uUkmr)}
                    rating={"two"}
                  />
                }
                tags={
                  <Button
                    colors={"lightGray"}
                    size={"small"}
                    submitsForm={true}
                  >
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bxChp
                  )}
                >
                  {"Club C 85 Vintage Men's Shoes"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__eWz5L
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__ssfFf)}
                dollars={"99"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe17.png",
                  fullWidth: 864,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__vHpc5)}
                    rating={"four"}
                  />
                }
                tags={
                  <Button
                    colors={"lightGray"}
                    size={"small"}
                    submitsForm={true}
                  >
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wxRfr
                  )}
                >
                  {"Nike Air Max Genome"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__b5Nr7
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__fjzOr)}
                dollars={"79"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe18.png",
                  fullWidth: 840,
                  fullHeight: 840,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__aeWmK)}
                    rating={"five"}
                  />
                }
                tags={
                  <Button
                    colors={"lightGray"}
                    size={"small"}
                    submitsForm={true}
                  >
                    {"New"}
                  </Button>
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__oH8Np
                  )}
                >
                  {"ULTRABOOST DNA 1.0 SHOES"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gkLQq
                  )}
                >
                  {"If you can dream it, you can build it."}
                </div>
              </ProductCard>
              <ProductCard
                cents={"50"}
                className={classNames("__wab_instance", sty.productCard__bIxg4)}
                dollars={"65"}
                img={{
                  src: "/plasmic/commerce_landing_page/images/shoe19.png",
                  fullWidth: 864,
                  fullHeight: 1080,
                  aspectRatio: undefined
                }}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__o7U)}
                    rating={"threeHalf"}
                  />
                }
                tags={
                  <Button
                    colors={"lightGray"}
                    size={"small"}
                    submitsForm={true}
                  >
                    {"New"}
                  </Button>
                }
              />
            </Stack__>
          </section>
          <section className={classNames(projectcss.all, sty.section__uSz1T)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__hCdPn)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__a1QJv)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___07Lk5)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nx4Ji
                    )}
                  >
                    {"Our best shoe sale of the year"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jrrNj
                    )}
                  >
                    {
                      "Signature style. Unsurpassed quality and comfort. Now\u2019s the perfect time to save on iconic shoes."
                    }
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__wo0)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__d7Tdc
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>{"3 "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontStyle: "italic" }}
                      >
                        {"for"}
                      </span>
                      <React.Fragment>{" $169"}</React.Fragment>
                    </React.Fragment>
                  </div>
                  <Button
                    colors={"black"}
                    endIcon={
                      <RightArrowIcon
                        className={classNames(projectcss.all, sty.svg___3EWu4)}
                        role={"img"}
                      />
                    }
                    rounded={true}
                    showEndIcon={true}
                    size={"large"}
                    submitsForm={true}
                  >
                    {"Shop sale"}
                  </Button>
                </Stack__>
              </Stack__>
            </Stack__>
          </section>
          <EmojiValueProps
            data-plasmic-name={"emojiValueProps"}
            data-plasmic-override={overrides.emojiValueProps}
            className={classNames("__wab_instance", sty.emojiValueProps)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column__okdw3)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__v8Hjy
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__sZIut)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                      submitsForm={true}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__eeV8M)}
                  icon={
                    <PlaneIcon
                      className={classNames(projectcss.all, sty.svg__bEzWn)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1HGlz
                    )}
                  >
                    {"Worldwide shipping"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pcU4E
                    )}
                  >
                    {"Special financing and earn rewards."}
                  </div>
                </Value>
              </div>
              <div className={classNames(projectcss.all, sty.column__zDkZq)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__n0BAf
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__iXqB)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                      submitsForm={true}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__yTj3J)}
                  icon={
                    <DocumentIcon
                      className={classNames(projectcss.all, sty.svg__jGDcS)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__n9FsI
                    )}
                  >
                    {"30-day guarantee"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ezxKi
                    )}
                  >
                    {"Free return policy."}
                  </div>
                </Value>
              </div>
              <div className={classNames(projectcss.all, sty.column___3YZAl)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__nVfKz
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__rpPh)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                      submitsForm={true}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__uCbcp)}
                  icon={
                    <LockIcon
                      className={classNames(projectcss.all, sty.svg__smgF)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sD6H
                    )}
                  >
                    {"Secured payments"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dnXzZ
                    )}
                  >
                    {"We accept major credit cards."}
                  </div>
                </Value>
              </div>
            </Stack__>
          </EmojiValueProps>
          <section className={classNames(projectcss.all, sty.section__bnfTj)}>
            <div
              data-plasmic-name={"container42"}
              data-plasmic-override={overrides.container42}
              className={classNames(projectcss.all, sty.container42)}
            >
              {renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ipltc)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3IoZy
                      )}
                    >
                      {"Just added"}
                    </div>
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__psHPr
                      )}
                      colors={"link"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg___2Ah7)}
                          role={"img"}
                        />
                      }
                      showEndIcon={true}
                      submitsForm={true}
                    >
                      {"See more"}
                    </Button>
                  </div>
                ),
                value: args.container42
              })}
            </div>
            <div
              data-plasmic-name={"container5"}
              data-plasmic-override={overrides.container5}
              className={classNames(projectcss.all, sty.container5)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___5PBzz)}
              >
                <ProductCard
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe14.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__osRr
                    )}
                  >
                    {"ADIDAS ULTRABOOST DNA X LEGO\u00ae PLATES SHOES"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7HDAs
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___8GlZp
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe15.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__d3Pr0
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rs4Yw
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__qmEk4
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe16.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lXhda
                    )}
                  >
                    {"Club C 85 Vintage Men's Shoes"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oJo0P
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__rz6Ka
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe17.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1Vejq
                    )}
                  >
                    {"Nike Air Max Genome"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vtUs
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__utaaE
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe18.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__etUfl
                    )}
                  >
                    {"ULTRABOOST DNA 1.0 SHOES"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zDn1
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__gasbb
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe19.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                />
              </Stack__>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__vkjyJ)}>
            <Stack__
              as={"div"}
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              hasGap={true}
              className={classNames(projectcss.all, sty.container6)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__f2Bj)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__i7Ifb
                  )}
                >
                  {"Categories"}
                </div>
                <Button
                  className={classNames("__wab_instance", sty.button__ogMqz)}
                  states={"active"}
                  submitsForm={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zr1Ea
                    )}
                  >
                    {"All"}
                  </div>
                </Button>
                <Button
                  className={classNames("__wab_instance", sty.button__odmee)}
                  submitsForm={true}
                >
                  {"New"}
                </Button>
                <Button
                  className={classNames("__wab_instance", sty.button___0Sts)}
                  submitsForm={true}
                >
                  {"Womens"}
                </Button>
                <Button
                  className={classNames("__wab_instance", sty.button__baMqW)}
                  submitsForm={true}
                >
                  {"Mens"}
                </Button>
                <Button
                  className={classNames("__wab_instance", sty.button___7WwKy)}
                  submitsForm={true}
                >
                  {"Kids"}
                </Button>
                <Button
                  className={classNames("__wab_instance", sty.button__agp7E)}
                  submitsForm={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bPrNo
                    )}
                  >
                    {"On sale"}
                  </div>
                </Button>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__chPed)}
              >
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__rhoUk
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe8.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dy3Qn
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38 Limited Edition"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gn98
                    )}
                  >
                    {"Women's Running Shoe"}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__wrdGx
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe7.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vrJ85
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__szJy
                    )}
                  >
                    {"Continue the NMD legacy in these adidas NMD_R1 Shoes."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__ncYQx
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe6.png",
                    fullWidth: 320,
                    fullHeight: 320,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2PhiF
                    )}
                  >
                    {"Question Low Men's Basketball Shoes"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fwxsP
                    )}
                  >
                    {"Lace up fierce baller style."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__pukvA
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe5.png",
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xNr0M
                    )}
                  >
                    {"Cali Women's Sneakers"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mvQqC
                    )}
                  >
                    {"A sport style turned street classic."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__stHB
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe4.png",
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lfyuz
                    )}
                  >
                    {"MAGIC SPEED"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8YUf8
                    )}
                  >
                    {"mMade for racing or regular training runs."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__oh0P2
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe3.png",
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zMkdz
                    )}
                  >
                    {"Pride Chuck Taylor All Star"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__q8Cx
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__sZqZt
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe2.png",
                    fullWidth: 864,
                    fullHeight: 1080,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___4NMc3
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cmu8R
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames("__wab_instance", sty.productCard__n4L)}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe9.png",
                    fullWidth: 1024,
                    fullHeight: 768,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xWiLn
                    )}
                  >
                    {"GEL-Nimbus 22 Retro Tokyo"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tCWpR
                    )}
                  >
                    {"Enjoy comfort with each stride."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__tIweQ
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe10.png",
                    fullWidth: 964,
                    fullHeight: 898,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tmSdw
                    )}
                  >
                    {"A Bug's World Chuck Taylor All Star"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cpI9
                    )}
                  >
                    {"Allover glow-in-the-dark bug prints."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__clLlM
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe11.png",
                    fullWidth: 766,
                    fullHeight: 766,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nmJfe
                    )}
                  >
                    {"NMD_R1 SHOES"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__p6D3R
                    )}
                  >
                    {
                      "Effortlessly step up your look than a pop of animal print."
                    }
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__keWfa
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe12.png",
                    fullWidth: 2000,
                    fullHeight: 2000,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__t46Y6
                    )}
                  >
                    {"Suede Teams Little Kids' Shoes"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___63Gv
                    )}
                  >
                    {"Worn by the icons of every generation."}
                  </div>
                </ProductCard>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard___19Fe0
                  )}
                  img={{
                    src: "/plasmic/commerce_landing_page/images/shoe13.png",
                    fullWidth: 840,
                    fullHeight: 840,
                    aspectRatio: undefined
                  }}
                  small={true}
                  tags={
                    <Button
                      colors={"lightGray"}
                      size={"small"}
                      submitsForm={true}
                    >
                      {"New"}
                    </Button>
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___8EvXn
                    )}
                  >
                    {"SUPERSTAR 360 PRIMEBLUE SANDALS"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__brUr7
                    )}
                  >
                    {"Your workhorse with wings returns."}
                  </div>
                </ProductCard>
              </Stack__>
            </Stack__>
          </section>
          <section className={classNames(projectcss.all, sty.section__nkxo2)}>
            <Stack__
              as={"div"}
              data-plasmic-name={"container434"}
              data-plasmic-override={overrides.container434}
              hasGap={true}
              className={classNames(projectcss.all, sty.container434)}
            >
              <Value
                center={true}
                children2={
                  <Button
                    className={classNames("__wab_instance", sty.button__q2Ygx)}
                    colors={"black"}
                    endIcon={
                      <RightArrowIcon
                        className={classNames(projectcss.all, sty.svg___7CNof)}
                        role={"img"}
                      />
                    }
                    rounded={true}
                    showEndIcon={true}
                    submitsForm={true}
                  >
                    {"Read our letter"}
                  </Button>
                }
                className={classNames("__wab_instance", sty.value__jtWfb)}
                icon={
                  <SpeakerphoneIcon
                    className={classNames(projectcss.all, sty.svg__snHGb)}
                    role={"img"}
                  />
                }
                topBottom={true}
                withButton={true}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mx2Rc
                  )}
                >
                  {"Our goals"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ts5At
                  )}
                >
                  {"We\u2019re learning how to become a new kind of company."}
                </div>
              </Value>
            </Stack__>
          </section>
          <section className={classNames(projectcss.all, sty.section___3QYqw)}>
            <Stack__
              as={"div"}
              data-plasmic-name={"container433"}
              data-plasmic-override={overrides.container433}
              hasGap={true}
              className={classNames(projectcss.all, sty.container433)}
            >
              <div className={classNames(projectcss.all, sty.column__qgcKg)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__huUyp
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__jpuni)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                      submitsForm={true}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__m0Ed8)}
                  icon={
                    <MedalIcon
                      className={classNames(projectcss.all, sty.svg__q0PWx)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dwTs
                    )}
                  >
                    {"We guarantee everything we sell."}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gyPfv
                    )}
                  >
                    {
                      "Ad fringilla ut nisi in hendrerit malesuada nascetur a in ridiculus."
                    }
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button__l0UIi)}
                    colors={"link"}
                    submitsForm={true}
                  >
                    {"View guarantee"}
                  </Button>
                </Value>
              </div>
              <div className={classNames(projectcss.all, sty.column__vw89)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__kdgjS
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___2H94F
                          )}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                      submitsForm={true}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__c4Yip)}
                  icon={
                    <LeafIcon
                      className={classNames(projectcss.all, sty.svg__nbKd)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ot2Ev
                    )}
                  >
                    {"Know how your shoes are made."}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__cvZuf
                    )}
                  >
                    {
                      "Parturient blandit viverra blandit sem suspendisse himenaeos."
                    }
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button__d6I0Y)}
                    colors={"link"}
                    submitsForm={true}
                  />
                </Value>
              </div>
              <div className={classNames(projectcss.all, sty.column__auDue)}>
                <Value
                  children2={
                    <Button
                      className={classNames("__wab_instance", sty.button__cKF)}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(projectcss.all, sty.svg__j3Yye)}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                      submitsForm={true}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__zAug)}
                  icon={
                    <ShoeIcon
                      className={classNames(projectcss.all, sty.svg__fx83O)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__x5Gh6
                    )}
                  >
                    {"Keep your shoes in play."}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yxhbH
                    )}
                  >
                    {
                      "Adipiscing ornare dui tellus nam nibh cum a torquent maecenas."
                    }
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button___7Lpvk)}
                    colors={"link"}
                    submitsForm={true}
                  />
                </Value>
              </div>
              <div className={classNames(projectcss.all, sty.column__x5YV)}>
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__zkn46
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___25ZeU
                          )}
                          role={"img"}
                        />
                      }
                      rounded={true}
                      size={"large"}
                      submitsForm={true}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__zyOO)}
                  icon={
                    <PeaceIcon
                      className={classNames(projectcss.all, sty.svg__qPwJt)}
                      role={"img"}
                    />
                  }
                  topBottom={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0WXx1
                    )}
                  >
                    {"We give back for every sale."}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9Rg0O
                    )}
                  >
                    {
                      "Parturient vestibulum ut a dui parturient habitant netus integer ipsum."
                    }
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button__xj9Mg)}
                    colors={"link"}
                    submitsForm={true}
                  />
                </Value>
              </div>
            </Stack__>
          </section>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "container3",
    "h1",
    "container4",
    "container",
    "emojiValueProps",
    "columns",
    "container42",
    "container5",
    "container6",
    "container434",
    "container433",
    "footer"
  ],
  navBar: ["navBar"],
  container3: ["container3", "h1"],
  h1: ["h1"],
  container4: ["container4"],
  container: ["container"],
  emojiValueProps: ["emojiValueProps", "columns"],
  columns: ["columns"],
  container42: ["container42"],
  container5: ["container5"],
  container6: ["container6"],
  container434: ["container434"],
  container433: ["container433"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: typeof NavBar;
  container3: "div";
  h1: "h1";
  container4: "div";
  container: "div";
  emojiValueProps: typeof EmojiValueProps;
  columns: "div";
  container42: "div";
  container5: "div";
  container6: "div";
  container434: "div";
  container433: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    container3: makeNodeComponent("container3"),
    h1: makeNodeComponent("h1"),
    container4: makeNodeComponent("container4"),
    container: makeNodeComponent("container"),
    emojiValueProps: makeNodeComponent("emojiValueProps"),
    columns: makeNodeComponent("columns"),
    container42: makeNodeComponent("container42"),
    container5: makeNodeComponent("container5"),
    container6: makeNodeComponent("container6"),
    container434: makeNodeComponent("container434"),
    container433: makeNodeComponent("container433"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "ShoeShop",
      description:
        "Ad ullamcorper eros nibh pharetra vulputate imperdiet consectetur vestibulum at ac posuere volutpat maecenas gravida dictum suscipit habitasse class scelerisque fermentum blandit mi a.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
